### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by thorade** [sdu-cfei/modest-py#38]
I suggest changing the header of EVERY file to the following:

```python
# -*- coding: utf-8 -*-

"""
Copyright (c) 2017, University of Southern Denmark
All rights reserved.
This code is licensed under BSD 2-clause license.
See LICENSE file in the project root for license terms.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# original script below
```

As discussed e.g. here:
http://python-future.org/quickstart.html
https://www.digitalocean.com/community/tutorials/how-to-port-python-2-code-to-python-3

**Comment by krzysztofarendt** [comment]
Yes, thanks, I'll do it this week.

**Comment by krzysztofarendt** [comment]
Fixed: https://github.com/sdu-cfei/modest-py/pull/39

**Comment by thorade** [comment]
I believe the latest pyFMI is also Py3 compatible, but they did not yet make an official release, same for Assimulo. Maybe ask for a new release on their forum?

I assume you are aware of https://github.com/CATIA-Systems/FMPy

**Comment by krzysztofarendt** [comment]
Python 3 compatibility would be great, I'll check their forum.

I know about FMPy, but did not have time to test it yet. Have you tested it? It looks promising.

**Comment by thorade** [comment]
I have not yet tested FMPy, I only heard about it and it is Py2 and Py3 compatible.

**Comment by krzysztofarendt** [comment]
OK, I have it on my TODO list :)

**Comment by krzysztofarendt** [comment]
http://jmodelica.org/10417#comment-6642

**Comment by thorade** [comment]
http://jmodelica.org/27800

**Comment by krzysztofarendt** [comment]
Also, we got the answer: http://www.jmodelica.org/10417#comment-6643
