### ISSUE TITLE
PEP8, flake8, autopep8

### ISSUE THREAD

**Issue by thorade** [sdu-cfei/modest-py#46]
For Python code there is the comprehensive style guide **PEP8**:
https://www.python.org/dev/peps/pep-0008/

**flake8** can be used to check the code,
**autopep8** can be used to fix most of the issues.
Both are installable from PyPI:
```
python -m pip install -U flake8 autopep8
```

Then, `cd` to the directory and run the following commands to get some harmless whitespace changes:
```
cd modest-py
flake8 --count --max-line-length=200 --statistics -qq
autopep8 --in-place --recursive --max-line-length=200 --select="E101,W1,W2" .
```
After that, check the git diff (with and without ignoring whitespace changes) and commit.  
If more cleaning is desired, run
```
flake8 --count --max-line-length=200 --statistics -qq
autopep8 --in-place --recursive --max-line-length=200 --select="E101,E3,W1,W2,W3" .
autopep8 --in-place --recursive --max-line-length=200 .
autopep8 --in-place --recursive --max-line-length=200 --aggressive --aggressive --aggressive .
```
Or select single rules and check the git diff after each rule to see what changed.

**Comment by krzysztofarendt** [comment]
Thanks, I will revise the code using this procedure.

**Comment by krzysztofarendt** [comment]
Drop a comment in case you start working on this. Otherwise I hope to find some time before Christmas.

**Comment by thorade** [comment]
There is no hurry, it is just style, it does not change the functionality. But it might increase readability.
I am not planning any further Pull Requests for this.

**Comment by krzysztofarendt** [comment]
Done: https://github.com/sdu-cfei/modest-py/commit/5fb95f05901b529dbbcfb1346733d5732c5d9ff1
