### ISSUE TITLE
Add FMPy support

### ISSUE THREAD

**Issue by krzysztofarendt** [sdu-cfei/modest-py#52]
Add FMPy support: https://github.com/CATIA-Systems/FMPy/tree/master/fmpy

**Comment by krzysztofarendt** [comment]
This is not needed, since PyFMI already supports Python 3 and can be installed via [conda](https://anaconda.org/chria/pyfmi).

**Comment by traversaro** [comment]
First of all, thanks for the great library! 

Just to add a note about this: one advantage of `fmpy` over `PyFMI` is that it can be easily installed with stock `pip` without the need to use Anaconda. simplifying deployment of the standard system python.

**Comment by krzysztofarendt** [comment]
Thanks @traversaro, that's a fair point. I reopened the issue, but don't have time to work on it now. It would be probably nice to have a support for both.

Maybe someone would like to look into it?

I think the only class that needs to be adapted is this one:
https://github.com/sdu-cfei/modest-py/blob/master/modestpy/fmi/model.py

**Comment by traversaro** [comment]
Thanks @krzysztofarendt . I personally do not have time to look into this right now, but I think having an open issue on this is a starting point, thanks!

**Comment by IvannikovG** [comment]
Hi!
If someone knows how to replace pyFMI for fmPY in modestpy please update!

**Comment by krzysztofarendt** [comment]
We will work on this on this branch: https://github.com/sdu-cfei/modest-py/tree/issue_52_add_fmpy

**Comment by krzysztofarendt** [comment]
The file that needs to be changes is: https://github.com/sdu-cfei/modest-py/blob/master/modestpy/fmi/model.py
