### ISSUE TITLE
FMU created with OpenModelica

### ISSUE THREAD

**Issue by triccyx** [sdu-cfei/modest-py#58]
When using an FMU created with OpenModelica the identification process result is a crash.

Environment:

- Ubuntu 16.04
- OpenModelica compiled from last source OMEdit v1.13.0-dev.214+gb23d97a
- FMU type tried with both co-simulation and model-exchange FMU version2 and both dynamic lib and static lib
- Modest-py from latest git

Test:

- I have substituted the Simple2R1C_ic_linux64.fmu in example/simple/resource with the same compiled with OpenModelica.
- I have run the simple.py test 
- The result is a crash
- I have put the original file Simple2R1C_ic_linux64.fmu back to  example/simple/resource, the identification process gives me a result

Files in attach:

- simple.log: the modest-py log when the failure occours
- screenlog.log: the screen log dumped to file when the failure occours
- Simple2R1C_ic_linux64.fmu.zip: the FMU compiled with OpenModelica

[simple.log](https://github.com/sdu-cfei/modest-py/files/2541690/simple.log)
[Simple2R1C_ic_linux64.fmu.zip](https://github.com/sdu-cfei/modest-py/files/2541693/Simple2R1C_ic_linux64.fmu.zip)
[screenlog.log](https://github.com/sdu-cfei/modest-py/files/2541833/screenlog.log)

**Comment by traversaro** [comment]
It seems that the FMU is loaded successfully once, and then the crash happens when the FMI is loaded again. Perhaps it is a OpenModelica problem related to loading the same FMU twice.

**Comment by krzysztofarendt** [comment]
@triccyx, when I try to load your FMU I immediately get the following error:

`pyfmi.fmi.FMUException: Error loading the binary. Could not load the DLL: libSimulationRuntimeC.so: cannot open shared object file: No such file or directory`

I tried different things but I can't make it working.

However, in screenlog.log the last line says:
`Linear multistep method  : BDFJSON object expected ',' or '}', got: "lineEnd":282,"colSt`

This seems to be the same bug as the one reported here: [https://openmodelica.org/forum/default-topic/2341-pyfmi,-openmodelica-fmu,-and-ipython-json-involved](https://openmodelica.org/forum/default-topic/2341-pyfmi,-openmodelica-fmu,-and-ipython-json-involved)

I have little experience with OpenModelica, but I did the following test:

- I installed OpenModelica stable on Debian 9 using `sudo apt install openmodelica`, following [this](https://openmodelica.org/download/download-linux) website
- I generated an FMU from `Simple2R1C_ic.mo` example using these settings:
![fmi_settings](https://user-images.githubusercontent.com/16005748/47921151-31748700-deb4-11e8-85fc-ede88f2a2c4b.png)

The resulting FMU works fine for me. I attached it to this post. Can you please check this one?
[om_fmu.zip](https://github.com/sdu-cfei/modest-py/files/2542855/om_fmu.zip)

**Comment by traversaro** [comment]
I suspect the issue is that @triccyx is using a development version of OpenModelica, while @krzysztofarendt probably tested with the stable.

**Comment by triccyx** [comment]
I think this could not be the problem. I am using the FMU generated by  @krzysztofarendt.
