### ISSUE TITLE
FMUs stored in Temp folder

### ISSUE THREAD

**Issue by efjerb** [sdu-cfei/modest-py#84]
When I run Modestpy it appears that my temporary folder (_C:\Users\USER\AppData\Local\Temp_) gets filled with the different FMUs in folders with names such as _tmp9zz77pwi_. Recently it caused the program to stop, since the temporary folder was full. I would expect FMPy to remove the folder after simulation, but I don't know if this is controlled by FMPy or Modestpy?

**Comment by krzysztofarendt** [comment]
@efjerb , I am aware of this behavior. This is not controlled by Modestpy though.
I think this might be because Modestpy has an old version of FMPy in `requirements.txt`.

The current version of FMPy should be removing temp dirs: https://github.com/CATIA-Systems/FMPy/blob/b76dfc85c9308a18f152fc80059cc97b8a86324b/fmpy/simulation.py#L765

Try updating FMPy and please let me know if it helps.

**Comment by krzysztofarendt** [comment]
> @efjerb , I am aware of this behavior. This is not controlled by Modestpy though. I think this might be because Modestpy has an old version of FMPy in `requirements.txt`.
> 
> The current version of FMPy should be removing temp dirs: https://github.com/CATIA-Systems/FMPy/blob/b76dfc85c9308a18f152fc80059cc97b8a86324b/fmpy/simulation.py#L765
> 
> Try updating FMPy and please let me know if it helps.

Nope, it is probably my fault. I will fix it.

**Comment by krzysztofarendt** [comment]
Line creating a temp dir:
https://github.com/sdu-cfei/modest-py/blob/0fa5e44ed5d9807965ae04db73b26ac6f1c0ea60/modestpy/fmi/model.py#L41

Then simulation (called many times in Modestpy) is using this temp dir:
https://github.com/sdu-cfei/modest-py/blob/0fa5e44ed5d9807965ae04db73b26ac6f1c0ea60/modestpy/fmi/model.py#L165

Modestpy should collect temp dirs from all subprocesses and delete them at the end of optimization.

**Comment by krzysztofarendt** [comment]
Fixed in: https://github.com/sdu-cfei/modest-py/pull/85

**Comment by krzysztofarendt** [comment]
@efjerb , new version available on PyPi: https://pypi.org/project/modestpy/
`pip install -U modestpy`
